services:
  vizion_db:
    image: docker.io/library/postgres:17-alpine
    container_name: vizion_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vizion
    volumes:
      - vizion_prod_data:/var/lib/postgresql/data
    networks:
      - web_network

  vizion_api:
    build: .
    container_name: vizion_api
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_FLYWAY_ENABLED=false
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vizion_db:5432/vizion
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_COM_COGNIS_VIZION=DEBUG
    depends_on:
      - vizion_db
    networks:
      - web_network

volumes:
  vizion_prod_data:

networks:
  web_network:
    external: true
