ALTER TABLE public.empreiteira ADD COLUMN data_criacao NOT NULL TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.empreiteira ADD COLUMN data_atualizacao TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.empreiteira ADD COLUMN criado_por NOT NULL VARCHAR(255) DEFAULT 'SYSTEM';
ALTER TABLE public.empreiteira ADD COLUMN atualizado_por VARCHAR(255);