server:
  port: 8090

spring:
  application:
    name: buildup-api
    datasource:
      url: jdbc:postgresql://vizion_db:5432/vizion
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect