spring.application.name=buildup-api
spring.datasource.url=jdbc:postgresql://buildup.db.cognisgroup.cloud:19671/dev_buildup
spring.datasource.username=dev_buildup
spring.datasource.password=RP{oSdyEn.EzoG]qgtQXf_39])UyRH6n91g2:QF_Qjo9d2TLj;-poAyDb. Cz:TMpxr5Urjcc2MjEz; oAuPh41v71YKVzJ2)wc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect